<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />
    <PackageReference Include="MudBlazor" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToDo.Application\ToDo.Application.csproj" />
    <ProjectReference Include="..\ToDo.Domain\ToDo.Domain.csproj" />
    <ProjectReference Include="..\ToDo.Infrastructure\ToDo.Infrastructure.csproj" />
  </ItemGroup>

</Project>
